# Generated by Django 5.0.1 on 2024-04-13 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tutorrequest_receiver_and_more'),
        ('user', '0037_tutor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('days_attended', models.JSONField(default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tutor')),
            ],
        ),
    ]
