# Generated by Django 5.0.1 on 2024-04-13 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clientattendance'),
        ('user', '0037_tutor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorrating',
            name='user',
        ),
        migrations.AddField(
            model_name='tutorrating',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
