# Generated by Django 5.0.1 on 2024-04-13 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tutorrating_user_tutorrating_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrating',
            name='rating',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
