# Generated by Django 5.0.1 on 2024-04-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_rename_profile_image_tutor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
