# Generated by Django 5.0.1 on 2024-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_tutor_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
